from odoo import models, fields, api

class GetPoNew(models.Model):
    _name = 'getpo_new'

    order_number = fields.Char(string='Order Number')
    purchaseorderversion = fields.Char(string='Purchase Order Version')
    purchaseorderdate = fields.Date(string='Purchase Order Date')
    lastrevisiondate = fields.Date(string='Last Revision Date')
    currency = fields.Char(string='Currency')

    consigneename = fields.Char(string='Consignee Name')
    consigneename2 = fields.Char(string='Consignee Name 2')
    consigneename3 = fields.Char(string='Consignee Name 3')
    consigneeadd1 = fields.Char(string='Consignee Address 1')
    consigneeadd2 = fields.Char(string='Consignee Address 2')
    contactperson = fields.Char(string='Contact Person')

    contacttel = fields.Char(string='Contact Telephone')
    contactemail = fields.Char(string='Contact Email')
    suppliername = fields.Char(string='Supplier Name')
    supplieradd1 = fields.Char(string='Supplier Address 1')
    supplieradd2 = fields.Char(string='Supplier Address 2')
    suppliertel = fields.Char(string='Supplier Telephone')
    supplierfax = fields.Char(string='Supplier Fax')

    billtoname = fields.Char(string='Bill To Name')
    billtoname2 = fields.Char(string='Bill To Name 2')
    billtoname3 = fields.Char(string='Bill To Name 3')
    billtoadd1 = fields.Char(string='Bill To Address 1')
    billtoadd2 = fields.Char(string='Bill To Address 2')
    notifyadd1 = fields.Char(string='Notify Address 1')
    notifyadd2 = fields.Char(string='Notify Address 2')
    season = fields.Char(string='Season')
    endbuyeraccnt = fields.Char(string='End Buyer Account')
    endbuyer = fields.Char(string='End Buyer')

    incoterms = fields.Char(string='Inco Terms')
    incotermdesc = fields.Char(string='Inco Term Description')
    paymentmode = fields.Char(string='Payment Mode')
    deliveryaddresscode = fields.Char(string='Delivery Address Code')
    deliveryaddress = fields.Char(string='Delivery Address')
    headertext = fields.Char(string='Header Text')
    headernote = fields.Char(string='Header Note')
    ordermode = fields.Char(string='Order Mode')
    companycode = fields.Char(string='Company Code')
    initialreleasedate = fields.Date(string='Initial Release Date')
    initialreleasetime = fields.Char(string='Initial Release Time')
    finalreleasedate = fields.Date(string='Final Release Date')


    purchaseorderitem = fields.Char(string='Purchase Order Item')
    material_code = fields.Char(string='Material Code')
    Vendor_Material = fields.Char(string='Vendor Material')
    colorcode = fields.Char(string='Color Code')
    refmaterial = fields.Char(string='Reference Material')
    refmaterial2 = fields.Char(string='Reference Material 2')
    itemtext = fields.Char(string='Item Text')
    matpotext = fields.Char(string='Material PO Text')

    pageformat = fields.Char(string='Page Format')
    materialdescription = fields.Char(string='Material Description')
    salesorder1 = fields.Char(string='Sales Order 1')
    salesorderitem = fields.Char(string='Sales Order Item')
    deliverydate1 = fields.Date(string='Delivery Date 1')
    quantity1 = fields.Char(string='Quantity 1')
    uom = fields.Char(string='UOM')
    netprice1 = fields.Char(string='Net Price 1')
    per = fields.Char(string='Per')
    discountpercentage = fields.Char(string='Discount Percentage')
    discountvalue = fields.Char(string='Discount Value')
    text = fields.Char(string='Text')
    producttype = fields.Char(string='Product Type')
    customerstyle = fields.Char(string='CustomerStyle')

    gender = fields.Char(string='Gender')
    orderreason = fields.Char(string='Order Reason')
    garmenttype = fields.Char(string='Garment Type')
    ptlcode = fields.Char(string='PTL Code')
    shipmode = fields.Char(string='Ship Mode')
    salesorderseason = fields.Char(string='Sales Order Season')
    buyyear = fields.Char(string='Buy Year')
    brand = fields.Char(string='Brand')
    departmentcode = fields.Char(string='Department Code')
    emotionalspace = fields.Char(string='Emotional Space')
    planninggroup = fields.Char(string='Planning Group')
    cpo = fields.Char(string='CPO')

    schedulelineno = fields.Char(string='Schedule Line No')
    gridvalue = fields.Char(string='Grid Value')
    deliverydate = fields.Date(string='Delivery Date')
    salesorder = fields.Char(string='Sales Order')
    overdeliverytolerance = fields.Char(string='Over Delivery Tolerance')
    underdeleverytol = fields.Char(string='Under Delivery Tolerance')
    quantity = fields.Char(string='Quantity')
    netprice = fields.Char(string='Net Price')
    netvalue = fields.Char(string='Net Value')
    venormaterialcode = fields.Char(string='Vendor Material Code')
    exfactorydate1 = fields.Char(string='Ex Factory Date 1')
    additionalskuno = fields.Char(string='Additional SKU Number')
    fg_size = fields.Char(string='FG Size')
    grid_value = fields.Char(string='grid_value')
    schedule_line_no = fields.Char(string='schedule_line_no')
    netvalue1 = fields.Char(string='Net Value 1')
    cusfield1 = fields.Char(string='Custom Field 1')
    CustomerStyleDesc = fields.Char(string = 'CustomerStyleDesc')
    ColorCode2 = fields.Char(string='COLOR CODE 2' , store=True)
